- type: group
  cache: 12h
  widgets:
    - &reddit-widget
      type: reddit
      subreddit: comics
      show-thumbnails: true
      app-auth:
        name: ${REDDIT_APP_NAME}
        id: ${REDDIT_APP_CLIENT_ID}
        secret: ${REDDIT_APP_SECRET}

    - <<: *reddit-widget
      subreddit: LocalLLaMA

    - <<: *reddit-widget
      subreddit: LocalLLM

    - <<: *reddit-widget
      subreddit: MurderedByWords

    - <<: *reddit-widget
      subreddit: FUCKYOUINPARTICULAR

    - <<: *reddit-widget
      subreddit: IAmA

    - <<: *reddit-widget
      subreddit: gaming

    - <<: *reddit-widget
      subreddit: LifeProTips

    - <<: *reddit-widget
      subreddit: explainlikeimfive

    - <<: *reddit-widget
      subreddit: oddlysatisfying

    - <<: *reddit-widget
      subreddit: nextfuckinglevel

    - <<: *reddit-widget
      subreddit: therewasanattempt

    - <<: *reddit-widget
      subreddit: ProgrammerHumor

    - <<: *reddit-widget
      subreddit: linux_gaming

    - <<: *reddit-widget
      subreddit: IWantToLearn

    - <<: *reddit-widget
      subreddit: wholesomememes

    - <<: *reddit-widget
      subreddit: worldnews

    - <<: *reddit-widget
      subreddit: AfterTheLoop

    - <<: *reddit-widget
      subreddit: devops

    - <<: *reddit-widget
      subreddit: computerscience

    - <<: *reddit-widget
      subreddit: bestof

    - <<: *reddit-widget
      subreddit: AdviceAnimals

    - <<: *reddit-widget
      subreddit: Arduboy

    - <<: *reddit-widget
      subreddit: AskHistorians

    - <<: *reddit-widget
      subreddit: askscience

    - <<: *reddit-widget
      subreddit: churning

    - <<: *reddit-widget
      subreddit: dating_advice

    - <<: *reddit-widget
      subreddit: DIY

    - <<: *reddit-widget
      subreddit: europe

    - <<: *reddit-widget
      subreddit: Fedora

    - <<: *reddit-widget
      subreddit: financialindependence

    - <<: *reddit-widget
      subreddit: IsItBullshit

    - <<: *reddit-widget
      subreddit: linux

    - <<: *reddit-widget
      subreddit: mac

    - <<: *reddit-widget
      subreddit: MacOS

    - <<: *reddit-widget
      subreddit: macsysadmin

    - <<: *reddit-widget
      subreddit: minilab

    - <<: *reddit-widget
      subreddit: MiniPCs

    - <<: *reddit-widget
      subreddit: MovieDetails

    - <<: *reddit-widget
      subreddit: opensource

    - <<: *reddit-widget
      subreddit: osx

    - <<: *reddit-widget
      subreddit: personalfinance

    - <<: *reddit-widget
      subreddit: pics

    - <<: *reddit-widget
      subreddit: politics

    - <<: *reddit-widget
      subreddit: productivity

    - <<: *reddit-widget
      subreddit: programming

    - <<: *reddit-widget
      subreddit: Python

    - <<: *reddit-widget
      subreddit: raspberry_pi

    - <<: *reddit-widget
      subreddit: retrogaming

    - <<: *reddit-widget
      subreddit: selfhosted

    - <<: *reddit-widget
      subreddit: selfimprovement

    - <<: *reddit-widget
      subreddit: technology

    - <<: *reddit-widget
      subreddit: todayilearned

    - <<: *reddit-widget
      subreddit: TooAfraidToAsk

    - <<: *reddit-widget
      subreddit: trippinthroughtime

    - <<: *reddit-widget
      subreddit: unixporn

    - <<: *reddit-widget
      subreddit: UpliftingNews

    - <<: *reddit-widget
      subreddit: YouShouldKnow

    - <<: *reddit-widget
      subreddit: Zig
