- type: rss
  collapse-after: 6
  limit: 20
  cache: 8h
  style: vertical-list
  feeds:
    - url: https://onefoottsunami.com/feed/json/
      title: One Foot Tsunami
    - url: https://selfh.st/rss/
      title: selfh.st
    - url: https://holdtherobot.com/blog/rss.xml
      title: Hold the Robot
    - url: https://feeds.allenpike.com/feed/
      title: Allen Pike
    - url: https://www.amusingplanet.com/feeds/posts/default?alt=rss
      title: Amusing Planet
    - url: https://feeds.arstechnica.com/arstechnica/index/
      title: Ars Technica
    - url: https://feeds.bbci.co.uk/news/world/rss.xml
      title: BBC News
    - url: https://www.thisiscolossal.com/feed/
      title: Colossal
    - url: https://furbo.org/feed/json
      title: furbo.org
    - url: https://jvns.ca/atom.xml
      title: Julia Evans
    - url: https://www.nomadicmatt.com/feed/
      title: Nomadic Matt
    - url: https://aworkinglibrary.com/feed/index.xml
      title: A Working Library
    - url: https://xkcd.com/rss.xml
      title: Xkcd
    - url: https://electrek.co/feed
      title: Electrek
    - url: https://www.wired.com/feed/rss
      title: Wired
    - url: https://www.theatlantic.com/feed/all/
      title: The Atlantic
    - url: https://www.vox.com/rss/index.xml
      title: Vox
    # - url: https://rss.app/feeds/hduqjWEyujKjSLFU.xml
    #   title: Inverse
    # - url: https://rss.app/feeds/bfMDGp1eFuIYj0SJ.xml
    #   title: Time Extension
    # - url: https://rss.app/feeds/OqcaWF1AZo4RmPyB.xml
    #   title: AP - US News
    # - url: https://rss.app/feeds/yPesgfLNjy2GRjxc.xml
    #   title: AP - Politics
