- type: markets
  markets:
    - symbol: VTI
      name: VTI
    - symbol: QQQ
      name: QQQ
    - symbol: AAPL
      name: AAPL
    - symbol: SEV
      name: SEV
    - symbol: ACHR
      name: Archer Aviation
    - symbol: JOBY
      name: Joby Aviation
    - symbol: V
      name: V
