# https://www.youtube.com/feed/subscriptions
# Click channel > Description > Share channel > Copy channel ID

- type: videos
  channels:
    - UC-kM5kL9CgjN9s9pim089gg  # @TheAdamConover
    - UC1E1SVcVyU3ntWMSQEp38Yw  # @TheProfGPod
    - UC3XTzVzaHQEd30rQbuvCtTQ  # @LastWeekTonight
    - UC8ENHE5xdFSwx71u3fDH5Xw  # @ThePrimeagen
    - UCajiMK_CY9icRhLepS8_3ug  # Alex Ziskind
    - UCarEovlrD9QY-fy-Z6apIDQ  # @HasanMinhaj
    - UCBa659QWEk1AI4Tg--mrJ2A  # @TomScottGo
    - UCBJycsmduvYEL83R_U4JriQ  # Marques Brownlee
    - UCCJFWxm9fUtB4hPzNvmfcMA  # @JamesMayDrinks
    - UCdld7SHk9IyYSkNrHA9B6Dw  # @AYEON
    - UCGwyQM5eQOTxoeHOZaMwzSg  # @track-star-show
    - UCLXo7UDZvByw2ixzpQCufnA  # @Vox
    - UCnxuOd8obvLLtf5_-YKFbiQ  # @EzraKleinShow
    - UCoZQiN0o7f36H7PaW4fVhFw  # @RetroGameCorps
    - UCQMELFlXQL38KPm8kM-4Adg  # @jaylenosgarage
    - UCR-DXc1voovS8nhAvccRZhg  # @JeffGeerling
    - UCsBjURrPoezykLs9EqgamOA  # @Fireshipio
    - UCsqjHFMB_JYTaEnf_vmTNqg  # @DougDeMuro
    - UCVhQ2NnY5Rskt6UjCUkJ_DA  # @ArjanCodes
    - UCXuqSBlHAE6Xw-yeJA0Tunw  # Linus Tech Tips
    - UCyoC6ap2VVf43aL2PxdxekA  # @ThisisGavinNewsom
